//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public decimal PhoneNUM { get; set; }
        public string NameONCard { get; set; }
        public int CardNumber { get; set; }
        public string SecurityCode { get; set; }
        public int Totaldistance { get; set; }
        public decimal NUMContainers { get; set; }
        public int Weight { get; set; }
        public int TotalPrice { get; set; }
    }
}
