//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaTransportation_ShowcassPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<decimal> PhoneNumber { get; set; }
        public string NameOnCard { get; set; }
        public Nullable<int> CardNumber { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<int> TotalDistance { get; set; }
        public Nullable<decimal> ContainersNumber { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ShipID { get; set; }
        public Nullable<int> ID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Ship Ship { get; set; }
    }
}
